# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Seleccion.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Seleccion import *
from Cuentas import *
from Seleccion_Cuenta import *
from funciones import *
import sys
from os import getcwd

class Ui_Seleccion_cta(object):
    def setupUi(self, Seleccion_cta):
        Seleccion_cta.setObjectName("Seleccion_cta")
        Seleccion_cta.resize(500, 247)
        Seleccion_cta.setWindowIcon(QtGui.QIcon("recursos/strong_doge.ico"))
        Seleccion_cta.setMinimumSize(QtCore.QSize(500, 247))
        Seleccion_cta.setMaximumSize(QtCore.QSize(500, 247))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 253, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 254, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(64, 126, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 169, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 253, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 254, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 253, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 254, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(64, 126, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 169, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 253, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 254, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(64, 126, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 253, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 254, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(64, 126, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 169, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(64, 126, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(64, 126, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 253, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 253, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 253, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        Seleccion_cta.setPalette(palette)
        self.centralwidget = QtWidgets.QWidget(Seleccion_cta)
        self.centralwidget.setObjectName("centralwidget")
        self.Label_bienvenida = QtWidgets.QLabel(self.centralwidget)
        self.Label_bienvenida.setGeometry(QtCore.QRect(30, 20, 461, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.Label_bienvenida.setFont(font)
        self.Label_bienvenida.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_bienvenida.setObjectName("Label_bienvenida")
        self.Boton_CtasPers = QtWidgets.QPushButton(self.centralwidget)
        self.Boton_CtasPers.setGeometry(QtCore.QRect(330, 120, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Boton_CtasPers.setFont(font)
        self.Boton_CtasPers.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Boton_CtasPers.setDefault(True)
        self.Boton_CtasPers.setObjectName("Boton_CtasPers")
        self.Boton_OtrasCtas = QtWidgets.QPushButton(self.centralwidget)
        self.Boton_OtrasCtas.setGeometry(QtCore.QRect(170, 120, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Boton_OtrasCtas.setFont(font)
        self.Boton_OtrasCtas.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Boton_OtrasCtas.setObjectName("Boton_OtrasCtas")
        self.Boton_Regresar = QtWidgets.QPushButton(self.centralwidget)
        self.Boton_Regresar.setGeometry(QtCore.QRect(30, 120, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Boton_Regresar.setFont(font)
        self.Boton_Regresar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Boton_Regresar.setObjectName("Boton_Regresar")

        self.Boton_Eliminar = QtWidgets.QPushButton(self.centralwidget)
        self.Boton_Eliminar.setGeometry(QtCore.QRect(175, 175, 120, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Boton_Eliminar.setFont(font)
        self.Boton_Eliminar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Boton_Eliminar.setObjectName("Boton_Eliminar")
        self.Boton_Eliminar.setText("Eliminar Usuario")


        self.Boton_Importar = QtWidgets.QPushButton(self.centralwidget)
        self.Boton_Importar.setGeometry(QtCore.QRect(50, 165, 61, 61))
        self.Boton_Importar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Boton_Importar.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("recursos/importar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Boton_Importar.setIcon(icon2)
        self.Boton_Importar.setIconSize(QtCore.QSize(42, 42))
        self.Boton_Importar.setObjectName("Boton_Importar")

        self.Boton_Exportar = QtWidgets.QPushButton(self.centralwidget)
        self.Boton_Exportar.setGeometry(QtCore.QRect(370, 165, 61, 61))
        self.Boton_Exportar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Boton_Exportar.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("recursos/exportar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Boton_Exportar.setIcon(icon2)
        self.Boton_Exportar.setIconSize(QtCore.QSize(42, 42))
        self.Boton_Exportar.setObjectName("Boton_Exportar")
        self.Boton_Exportar.setAccessibleDescription("Click para guardar las cuentas en un archivo")  


        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 60, 461, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        Seleccion_cta.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Seleccion_cta)
        self.statusbar.setObjectName("statusbar")
        Seleccion_cta.setStatusBar(self.statusbar)

        self.retranslateUi(Seleccion_cta)
        QtCore.QMetaObject.connectSlotsByName(Seleccion_cta)

        
        self.Boton_Regresar.clicked.connect(lambda: Seleccion_cta.close())

        self.Boton_CtasPers.clicked.connect(self.mostrar_cuentasp)
        self.Boton_OtrasCtas.clicked.connect(self.mostrar_cuentas_otras)
        self.Boton_Eliminar.clicked.connect(self.eliminar_usuario)
        self.Boton_Exportar.clicked.connect(self.exportar_cuentas)
        self.Boton_Importar.clicked.connect(self.importar_cuentas)

        ###Ventana Seleccion Cuenta
        self.Seleccion_Cuenta = QtWidgets.QMainWindow()
        self.ui_Selec_cta = Ui_Seleccion_Cuenta()

        #Ventana Cuentas Personales
        self.Cuentas = QtWidgets.QMainWindow()
        self.ui_Cuentas = Ui_Cuentas()
         
    def retranslateUi(self, Seleccion_cta):
        _translate = QtCore.QCoreApplication.translate
        Seleccion_cta.setWindowTitle(_translate("Seleccion_cta", "Opciones"))
        self.Label_bienvenida.setText(_translate("Seleccion_cta", "Bienvenido/a "+str(get_last_user())))
        self.Boton_CtasPers.setText(_translate("Seleccion_cta", "Cuentas Personales"))
        self.Boton_CtasPers.setShortcut(_translate("Seleccion_cta", "Return"))
        self.Boton_OtrasCtas.setText(_translate("Seleccion_cta", "Otras Cuentas"))
        self.Boton_Regresar.setText(_translate("Seleccion_cta", "Regresar"))
        self.Boton_Regresar.setShortcut(_translate("Seleccion_cta", "Esc"))
        self.label_2.setText(_translate("Seleccion_cta", "Elija una Opción"))


    def mostrar_cuentasp(self): 
        self.ui_Cuentas.setupUi(self.Cuentas,"personal","")   
        self.Cuentas.show()

    def mostrar_cuentas_otras(self):
        self.ui_Selec_cta.setupUi(self.Seleccion_Cuenta)
        self.Seleccion_Cuenta.show()
    
    def eliminar_usuario(self):
        buttonReply = QtWidgets.QMessageBox.question(QtWidgets.QMessageBox(), 'Eliminar Usuario', "Desea Eiminar su usuario y todas las cuentas asociadas?", QtWidgets.QMessageBox.Yes | QtWidgets.QMessageBox.No, QtWidgets.QMessageBox.No)
        if buttonReply == QtWidgets.QMessageBox.Yes:
            eliminar_usuario()
            boton_info("Usuario Eliminado Exitosamente!") 
            borr_tmp() 
            self.Boton_Regresar.click()
            
    def importar_cuentas(self):
        fname = QtWidgets.QFileDialog.getOpenFileName(self.centralwidget, 'Abrir Registros',getcwd(),"Archivo de Registros (*.xd)")
        r_nombre = fname[0]
        if len(r_nombre)>1:
            clave, done = QtWidgets.QInputDialog.getText(self.centralwidget, 'Verificación', 'Ingrese la clave de estos registros:') 
            if done:
                importacion(r_nombre,clave)
        print()


    def exportar_cuentas(self):
        fname = QtWidgets.QFileDialog.getSaveFileName(self.centralwidget, 'Guardar Registros',getcwd(),"Archivo de Registros (*.xd)")
        r_nombre = fname[0]
        if len(r_nombre)>1:
            exportar(r_nombre)
            boton_info("Registros Exportados Exitosamente!")
        
 
    

    



if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    Seleccion = QtWidgets.QMainWindow()
    ui = Ui_Seleccion_cta()
    ui.setupUi(Seleccion)
    Seleccion.show()
    sys.exit(app.exec_())



